<?php
define("DATABASE_HOST","localhost");

define("DATABASE_TRAVELEXPERTS","travelexperts");
define("DATABASE_TRAVELEXPERTS_USERNAME",'root');
define("DATABASE_TRAVELEXPERTS_PASSWORD",'');

//MYSQL CONNECTION ERRORS
define("DATABASE_QUERY_ERROR","1000");

 ?>
